# Generated by Django 5.0.4 on 2024-05-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='avatar',
            field=models.ImageField(blank=True, default='img/default_user_icon', null=True, upload_to='uploads/'),
        ),
    ]
