# Generated by Django 5.0.4 on 2024-05-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='avatar',
            field=models.ImageField(blank=True, default='uploads/default_user_icon.png', null=True, upload_to=''),
        ),
    ]
