# Generated by Django 5.0.4 on 2024-04-08 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_answer_author_alter_question_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeanswer',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.user_profile'),
        ),
        migrations.AlterField(
            model_name='likequestion',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.user_profile'),
        ),
    ]
