# Generated by Django 5.0.4 on 2024-04-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_likeanswer_user_alter_likequestion_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likeanswer',
            unique_together={('user', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='likequestion',
            unique_together={('user', 'question')},
        ),
    ]
